In [113]:
#This is to import the libraries
import pandas as pd 
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error, r2_score

In [76]:
#This is to download the Data
data_set=pd.read_csv('diabetic_data.csv')
data_set.columns
data_set

encounter_id  patient_nbr  ... diabetesMed readmitted
0            2278392      8222157  ...          No         NO
1             149190     55629189  ...         Yes        >30
2              64410     86047875  ...         Yes         NO
3             500364     82442376  ...         Yes         NO
4              16680     42519267  ...         Yes         NO
...              ...          ...  ...         ...        ...
101761     443847548    100162476  ...         Yes        >30
101762     443847782     74694222  ...         Yes         NO
101763     443854148     41088789  ...         Yes         NO
101764     443857166     31693671  ...         Yes         NO
101765     443867222    175429310  ...          No         NO

[101766 rows x 50 columns]

In [77]:
#These are the Independent and Dependent variables
x=data_set.iloc[:, [2, 3, 9, 12, 13, 14, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 46]].values
y=data_set.iloc[:, 47:48].values
print(x)
print(y)

[['Caucasian' 'Female' 1 ... 'No' 'No' 'No']
 ['Caucasian' 'Female' 3 ... 'No' 'No' 'No']
 ['AfricanAmerican' 'Female' 2 ... 'No' 'No' 'No']
 ...
 ['Caucasian' 'Male' 1 ... 'No' 'No' 'No']
 ['Caucasian' 'Female' 10 ... 'No' 'No' 'No']
 ['Caucasian' 'Male' 6 ... 'No' 'No' 'No']]
[['No']
 ['Ch']
 ['No']
 ...
 ['Ch']
 ['Ch']
 ['No']]


In [78]:
#This is to change the Race into a number.
le=LabelEncoder()
x[:,0]=le.fit_transform(x[:,0])
print(x)

[[3 'Female' 1 ... 'No' 'No' 'No']
 [3 'Female' 3 ... 'No' 'No' 'No']
 [1 'Female' 2 ... 'No' 'No' 'No']
 ...
 [3 'Male' 1 ... 'No' 'No' 'No']
 [3 'Female' 10 ... 'No' 'No' 'No']
 [3 'Male' 6 ... 'No' 'No' 'No']]


In [79]:
#This is to change the Gender into a number.
le=LabelEncoder()
x[:,1]=le.fit_transform(x[:,1])
print(x)

[[3 0 1 ... 'No' 'No' 'No']
 [3 0 3 ... 'No' 'No' 'No']
 [1 0 2 ... 'No' 'No' 'No']
 ...
 [3 1 1 ... 'No' 'No' 'No']
 [3 0 10 ... 'No' 'No' 'No']
 [3 1 6 ... 'No' 'No' 'No']]


In [80]:
#This is to change the max_glu_serum into a number.
le=LabelEncoder()
x[:,6]=le.fit_transform(x[:,6])
print(x)

[[3 0 1 ... 'No' 'No' 'No']
 [3 0 3 ... 'No' 'No' 'No']
 [1 0 2 ... 'No' 'No' 'No']
 ...
 [3 1 1 ... 'No' 'No' 'No']
 [3 0 10 ... 'No' 'No' 'No']
 [3 1 6 ... 'No' 'No' 'No']]


In [81]:
#This is to change the Position into a number.
le=LabelEncoder()
x[:,7]=le.fit_transform(x[:,7])
print(x)

[[3 0 1 ... 'No' 'No' 'No']
 [3 0 3 ... 'No' 'No' 'No']
 [1 0 2 ... 'No' 'No' 'No']
 ...
 [3 1 1 ... 'No' 'No' 'No']
 [3 0 10 ... 'No' 'No' 'No']
 [3 1 6 ... 'No' 'No' 'No']]


In [82]:
#This is to change the Position into a number.
le=LabelEncoder()
x[:,8]=le.fit_transform(x[:, 8])
print(x)

[[3 0 1 ... 'No' 'No' 'No']
 [3 0 3 ... 'No' 'No' 'No']
 [1 0 2 ... 'No' 'No' 'No']
 ...
 [3 1 1 ... 'No' 'No' 'No']
 [3 0 10 ... 'No' 'No' 'No']
 [3 1 6 ... 'No' 'No' 'No']]


In [83]:
#This is to change the Position into a number.
le=LabelEncoder()
x[:,9]=le.fit_transform(x[:,9])
print(x)

[[3 0 1 ... 'No' 'No' 'No']
 [3 0 3 ... 'No' 'No' 'No']
 [1 0 2 ... 'No' 'No' 'No']
 ...
 [3 1 1 ... 'No' 'No' 'No']
 [3 0 10 ... 'No' 'No' 'No']
 [3 1 6 ... 'No' 'No' 'No']]


In [84]:
#This is to change the Position into a number.
le=LabelEncoder()
x[:,10]=le.fit_transform(x[:,10])
print(x)

[[3 0 1 ... 'No' 'No' 'No']
 [3 0 3 ... 'No' 'No' 'No']
 [1 0 2 ... 'No' 'No' 'No']
 ...
 [3 1 1 ... 'No' 'No' 'No']
 [3 0 10 ... 'No' 'No' 'No']
 [3 1 6 ... 'No' 'No' 'No']]


In [85]:
#This is to change the Position into a number.
le=LabelEncoder()
x[:,11]=le.fit_transform(x[:,11])
print(x)

[[3 0 1 ... 'No' 'No' 'No']
 [3 0 3 ... 'No' 'No' 'No']
 [1 0 2 ... 'No' 'No' 'No']
 ...
 [3 1 1 ... 'No' 'No' 'No']
 [3 0 10 ... 'No' 'No' 'No']
 [3 1 6 ... 'No' 'No' 'No']]


In [86]:
#This is to change the Position into a number.
le=LabelEncoder()
x[:,12]=le.fit_transform(x[:,12])
print(x)

[[3 0 1 ... 'No' 'No' 'No']
 [3 0 3 ... 'No' 'No' 'No']
 [1 0 2 ... 'No' 'No' 'No']
 ...
 [3 1 1 ... 'No' 'No' 'No']
 [3 0 10 ... 'No' 'No' 'No']
 [3 1 6 ... 'No' 'No' 'No']]


In [87]:
#This is to change the Position into a number.
le=LabelEncoder()
x[:,13]=le.fit_transform(x[:,13])
print(x)

[[3 0 1 ... 'No' 'No' 'No']
 [3 0 3 ... 'No' 'No' 'No']
 [1 0 2 ... 'No' 'No' 'No']
 ...
 [3 1 1 ... 'No' 'No' 'No']
 [3 0 10 ... 'No' 'No' 'No']
 [3 1 6 ... 'No' 'No' 'No']]


In [88]:
#This is to change the Position into a number.
le=LabelEncoder()
x[:,14]=le.fit_transform(x[:,14])
print(x)

[[3 0 1 ... 'No' 'No' 'No']
 [3 0 3 ... 'No' 'No' 'No']
 [1 0 2 ... 'No' 'No' 'No']
 ...
 [3 1 1 ... 'No' 'No' 'No']
 [3 0 10 ... 'No' 'No' 'No']
 [3 1 6 ... 'No' 'No' 'No']]


In [89]:
#This is to change the Position into a number.
le=LabelEncoder()
x[:,15]=le.fit_transform(x[:,15])
print(x)

[[3 0 1 ... 'No' 'No' 'No']
 [3 0 3 ... 'No' 'No' 'No']
 [1 0 2 ... 'No' 'No' 'No']
 ...
 [3 1 1 ... 'No' 'No' 'No']
 [3 0 10 ... 'No' 'No' 'No']
 [3 1 6 ... 'No' 'No' 'No']]


In [90]:
#This is to change the Position into a number.
le=LabelEncoder()
x[:,16]=le.fit_transform(x[:,16])
print(x)

[[3 0 1 ... 'No' 'No' 'No']
 [3 0 3 ... 'No' 'No' 'No']
 [1 0 2 ... 'No' 'No' 'No']
 ...
 [3 1 1 ... 'No' 'No' 'No']
 [3 0 10 ... 'No' 'No' 'No']
 [3 1 6 ... 'No' 'No' 'No']]


In [91]:
#This is to change the Position into a number.
le=LabelEncoder()
x[:,17]=le.fit_transform(x[:,17])
print(x)

[[3 0 1 ... 'No' 'No' 'No']
 [3 0 3 ... 'No' 'No' 'No']
 [1 0 2 ... 'No' 'No' 'No']
 ...
 [3 1 1 ... 'No' 'No' 'No']
 [3 0 10 ... 'No' 'No' 'No']
 [3 1 6 ... 'No' 'No' 'No']]


In [92]:
#This is to change the Position into a number.
le=LabelEncoder()
x[:,18]=le.fit_transform(x[:,18])
print(x)

[[3 0 1 ... 'No' 'No' 'No']
 [3 0 3 ... 'No' 'No' 'No']
 [1 0 2 ... 'No' 'No' 'No']
 ...
 [3 1 1 ... 'No' 'No' 'No']
 [3 0 10 ... 'No' 'No' 'No']
 [3 1 6 ... 'No' 'No' 'No']]


In [93]:
#This is to change the Position into a number.
le=LabelEncoder()
x[:,19]=le.fit_transform(x[:,19])
print(x)

[[3 0 1 ... 'No' 'No' 'No']
 [3 0 3 ... 'No' 'No' 'No']
 [1 0 2 ... 'No' 'No' 'No']
 ...
 [3 1 1 ... 'No' 'No' 'No']
 [3 0 10 ... 'No' 'No' 'No']
 [3 1 6 ... 'No' 'No' 'No']]


In [94]:
#This is to change the Position into a number.
le=LabelEncoder()
x[:,20]=le.fit_transform(x[:,20])
print(x)

[[3 0 1 ... 'No' 'No' 'No']
 [3 0 3 ... 'No' 'No' 'No']
 [1 0 2 ... 'No' 'No' 'No']
 ...
 [3 1 1 ... 'No' 'No' 'No']
 [3 0 10 ... 'No' 'No' 'No']
 [3 1 6 ... 'No' 'No' 'No']]


In [95]:
#This is to change the Position into a number.
le=LabelEncoder()
x[:,21]=le.fit_transform(x[:,21])
print(x)

[[3 0 1 ... 'No' 'No' 'No']
 [3 0 3 ... 'No' 'No' 'No']
 [1 0 2 ... 'No' 'No' 'No']
 ...
 [3 1 1 ... 'No' 'No' 'No']
 [3 0 10 ... 'No' 'No' 'No']
 [3 1 6 ... 'No' 'No' 'No']]


In [96]:
#This is to change the Position into a number.
le=LabelEncoder()
x[:,22]=le.fit_transform(x[:,22])
print(x)

[[3 0 1 ... 'No' 'No' 'No']
 [3 0 3 ... 'No' 'No' 'No']
 [1 0 2 ... 'No' 'No' 'No']
 ...
 [3 1 1 ... 'No' 'No' 'No']
 [3 0 10 ... 'No' 'No' 'No']
 [3 1 6 ... 'No' 'No' 'No']]


In [97]:
#This is to change the Position into a number.
le=LabelEncoder()
x[:,23]=le.fit_transform(x[:,23])
print(x)

[[3 0 1 ... 'No' 'No' 'No']
 [3 0 3 ... 'No' 'No' 'No']
 [1 0 2 ... 'No' 'No' 'No']
 ...
 [3 1 1 ... 'No' 'No' 'No']
 [3 0 10 ... 'No' 'No' 'No']
 [3 1 6 ... 'No' 'No' 'No']]


In [98]:
#This is to change the Position into a number.
le=LabelEncoder()
x[:,24]=le.fit_transform(x[:,24])
print(x)

[[3 0 1 ... 'No' 'No' 'No']
 [3 0 3 ... 'No' 'No' 'No']
 [1 0 2 ... 'No' 'No' 'No']
 ...
 [3 1 1 ... 'No' 'No' 'No']
 [3 0 10 ... 'No' 'No' 'No']
 [3 1 6 ... 'No' 'No' 'No']]


In [99]:
#This is to change the Position into a number.
le=LabelEncoder()
x[:,25]=le.fit_transform(x[:,25])
print(x)

[[3 0 1 ... 'No' 'No' 'No']
 [3 0 3 ... 'No' 'No' 'No']
 [1 0 2 ... 'No' 'No' 'No']
 ...
 [3 1 1 ... 'No' 'No' 'No']
 [3 0 10 ... 'No' 'No' 'No']
 [3 1 6 ... 'No' 'No' 'No']]


In [100]:
#This is to change the Position into a number.
le=LabelEncoder()
x[:,26]=le.fit_transform(x[:,26])
print(x)

[[3 0 1 ... 'No' 'No' 'No']
 [3 0 3 ... 'No' 'No' 'No']
 [1 0 2 ... 'No' 'No' 'No']
 ...
 [3 1 1 ... 'No' 'No' 'No']
 [3 0 10 ... 'No' 'No' 'No']
 [3 1 6 ... 'No' 'No' 'No']]


In [101]:
#This is to change the Position into a number.
le=LabelEncoder()
x[:,27]=le.fit_transform(x[:,27])
print(x)

[[3 0 1 ... 'No' 'No' 'No']
 [3 0 3 ... 'No' 'No' 'No']
 [1 0 2 ... 'No' 'No' 'No']
 ...
 [3 1 1 ... 'No' 'No' 'No']
 [3 0 10 ... 'No' 'No' 'No']
 [3 1 6 ... 'No' 'No' 'No']]


In [102]:
#This is to change the Position into a number.
le=LabelEncoder()
x[:,28]=le.fit_transform(x[:,28])
print(x)

[[3 0 1 ... 0 'No' 'No']
 [3 0 3 ... 0 'No' 'No']
 [1 0 2 ... 0 'No' 'No']
 ...
 [3 1 1 ... 0 'No' 'No']
 [3 0 10 ... 0 'No' 'No']
 [3 1 6 ... 0 'No' 'No']]


In [103]:
#This is to change the Position into a number.
le=LabelEncoder()
x[:,29]=le.fit_transform(x[:,29])
print(x)

[[3 0 1 ... 0 0 'No']
 [3 0 3 ... 0 0 'No']
 [1 0 2 ... 0 0 'No']
 ...
 [3 1 1 ... 0 0 'No']
 [3 0 10 ... 0 0 'No']
 [3 1 6 ... 0 0 'No']]


In [104]:
#This is to change the Position into a number.
le=LabelEncoder()
x[:,30]=le.fit_transform(x[:,30])
print(x)

[[3 0 1 ... 0 0 0]
 [3 0 3 ... 0 0 0]
 [1 0 2 ... 0 0 0]
 ...
 [3 1 1 ... 0 0 0]
 [3 0 10 ... 0 0 0]
 [3 1 6 ... 0 0 0]]


In [107]:
#This is to change the Position into a number.
le=LabelEncoder()
y=le.fit_transform(y)
print(y)

[1 0 1 ... 0 0 1]


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [108]:
#This is to split the training data.
x_train, x_test, y_train, y_test=train_test_split(x,y, test_size=0.2, random_state=3)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[[1 1 7 ... 0 0 0]
 [3 1 3 ... 0 0 0]
 [3 1 4 ... 0 0 0]
 ...
 [3 0 8 ... 0 0 0]
 [3 1 5 ... 0 0 0]
 [3 0 5 ... 0 0 0]]
[[3 0 7 ... 0 0 0]
 [3 1 2 ... 0 0 0]
 [1 1 3 ... 0 0 0]
 ...
 [3 0 4 ... 0 0 0]
 [3 0 6 ... 0 0 0]
 [3 1 2 ... 0 0 0]]
[0 0 1 ... 0 0 1]
[0 0 1 ... 1 1 1]


In [109]:
# This is to train
regr_1 = DecisionTreeRegressor(max_depth=2)
regr_1.fit(x, y)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=2,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [110]:
regressor=DecisionTreeRegressor(criterion="mse")
regressor.fit(x,y)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [120]:
#This is to test the model
y_pred=regr_1.predict(x_test)
print(y_pred)

[0.         0.         0.69990541 ... 0.69990541 0.69990541 0.69990541]


In [121]:
#Mean squared Error
mse=mean_squared_error(y_test, y_pred)
print(mse)

0.16046486400404672


In [122]:
#R2 Score
r2score=r2_score(y_test, y_pred)
print(r2score)

0.3548117905525565
